export const ADDRESSING_MODES = Object.freeze({
  IMPLIED: 'imp',
  ACCUMULATOR: 'acc',
  IMMEDIATE: 'imm',
  ZERO_PAGE: 'zp',
  ZERO_PAGE_X: 'zpX',
  ZERO_PAGE_Y: 'zpY',
  ABSOLUTE: 'abs',
  ABSOLUTE_X: 'absX',
  ABSOLUTE_Y: 'absY',
  INDIRECT: 'ind',
  INDIRECT_X: 'indX',
  INDIRECT_Y: 'indY',
  RELATIVE: 'rel'
});

export const ADDRESSING_MODE_LENGTHS = Object.freeze({
  [ADDRESSING_MODES.IMPLIED]: 1,
  [ADDRESSING_MODES.ACCUMULATOR]: 1,
  [ADDRESSING_MODES.IMMEDIATE]: 2,
  [ADDRESSING_MODES.ZERO_PAGE]: 2,
  [ADDRESSING_MODES.ZERO_PAGE_X]: 2,
  [ADDRESSING_MODES.ZERO_PAGE_Y]: 2,
  [ADDRESSING_MODES.ABSOLUTE]: 3,
  [ADDRESSING_MODES.ABSOLUTE_X]: 3,
  [ADDRESSING_MODES.ABSOLUTE_Y]: 3,
  [ADDRESSING_MODES.INDIRECT]: 3,
  [ADDRESSING_MODES.INDIRECT_X]: 2,
  [ADDRESSING_MODES.INDIRECT_Y]: 2,
  [ADDRESSING_MODES.RELATIVE]: 2
});

export const ABSOLUTE_INDEX_REG_BY_MODE = Object.freeze({
  [ADDRESSING_MODES.ABSOLUTE_X]: 'X',
  [ADDRESSING_MODES.ABSOLUTE_Y]: 'Y'
});

export function absoluteIndexRegisterForMode(mode) {
  return ABSOLUTE_INDEX_REG_BY_MODE[mode] || null;
}
