import { ADDRESSING_MODES as AM } from './addressingModes.js';

// Official (documented) 6502 opcodes only; illegal/undocumented opcodes are null. 🤖
// The NES CPU (2A03/2A07) is based on NMOS 6502 but without decimal mode; the opcode map is still the same. 🤖

function op(mnemonic, mode) {
  return { mnemonic, mode };
}

// Addressing modes used by this project: 🤖
// imp, acc, imm, zp, zpX, zpY, abs, absX, absY, ind, indX, indY, rel 🤖

export const OPCODES = Array.from({ length: 256 }, () => null);

// 0x00 🤖
OPCODES[0x00] = op('BRK', AM.IMPLIED);
OPCODES[0x01] = op('ORA', AM.INDIRECT_X);
OPCODES[0x05] = op('ORA', AM.ZERO_PAGE);
OPCODES[0x06] = op('ASL', AM.ZERO_PAGE);
OPCODES[0x08] = op('PHP', AM.IMPLIED);
OPCODES[0x09] = op('ORA', AM.IMMEDIATE);
OPCODES[0x0A] = op('ASL', AM.ACCUMULATOR);
OPCODES[0x0D] = op('ORA', AM.ABSOLUTE);
OPCODES[0x0E] = op('ASL', AM.ABSOLUTE);

// 0x10 🤖
OPCODES[0x10] = op('BPL', AM.RELATIVE);
OPCODES[0x11] = op('ORA', AM.INDIRECT_Y);
OPCODES[0x15] = op('ORA', AM.ZERO_PAGE_X);
OPCODES[0x16] = op('ASL', AM.ZERO_PAGE_X);
OPCODES[0x18] = op('CLC', AM.IMPLIED);
OPCODES[0x19] = op('ORA', AM.ABSOLUTE_Y);
OPCODES[0x1D] = op('ORA', AM.ABSOLUTE_X);
OPCODES[0x1E] = op('ASL', AM.ABSOLUTE_X);

// 0x20 🤖
OPCODES[0x20] = op('JSR', AM.ABSOLUTE);
OPCODES[0x21] = op('AND', AM.INDIRECT_X);
OPCODES[0x24] = op('BIT', AM.ZERO_PAGE);
OPCODES[0x25] = op('AND', AM.ZERO_PAGE);
OPCODES[0x26] = op('ROL', AM.ZERO_PAGE);
OPCODES[0x28] = op('PLP', AM.IMPLIED);
OPCODES[0x29] = op('AND', AM.IMMEDIATE);
OPCODES[0x2A] = op('ROL', AM.ACCUMULATOR);
OPCODES[0x2C] = op('BIT', AM.ABSOLUTE);
OPCODES[0x2D] = op('AND', AM.ABSOLUTE);
OPCODES[0x2E] = op('ROL', AM.ABSOLUTE);

// 0x30 🤖
OPCODES[0x30] = op('BMI', AM.RELATIVE);
OPCODES[0x31] = op('AND', AM.INDIRECT_Y);
OPCODES[0x35] = op('AND', AM.ZERO_PAGE_X);
OPCODES[0x36] = op('ROL', AM.ZERO_PAGE_X);
OPCODES[0x38] = op('SEC', AM.IMPLIED);
OPCODES[0x39] = op('AND', AM.ABSOLUTE_Y);
OPCODES[0x3D] = op('AND', AM.ABSOLUTE_X);
OPCODES[0x3E] = op('ROL', AM.ABSOLUTE_X);

// 0x40 🤖
OPCODES[0x40] = op('RTI', AM.IMPLIED);
OPCODES[0x41] = op('EOR', AM.INDIRECT_X);
OPCODES[0x45] = op('EOR', AM.ZERO_PAGE);
OPCODES[0x46] = op('LSR', AM.ZERO_PAGE);
OPCODES[0x48] = op('PHA', AM.IMPLIED);
OPCODES[0x49] = op('EOR', AM.IMMEDIATE);
OPCODES[0x4A] = op('LSR', AM.ACCUMULATOR);
OPCODES[0x4C] = op('JMP', AM.ABSOLUTE);
OPCODES[0x4D] = op('EOR', AM.ABSOLUTE);
OPCODES[0x4E] = op('LSR', AM.ABSOLUTE);

// 0x50 🤖
OPCODES[0x50] = op('BVC', AM.RELATIVE);
OPCODES[0x51] = op('EOR', AM.INDIRECT_Y);
OPCODES[0x55] = op('EOR', AM.ZERO_PAGE_X);
OPCODES[0x56] = op('LSR', AM.ZERO_PAGE_X);
OPCODES[0x58] = op('CLI', AM.IMPLIED);
OPCODES[0x59] = op('EOR', AM.ABSOLUTE_Y);
OPCODES[0x5D] = op('EOR', AM.ABSOLUTE_X);
OPCODES[0x5E] = op('LSR', AM.ABSOLUTE_X);

// 0x60 🤖
OPCODES[0x60] = op('RTS', AM.IMPLIED);
OPCODES[0x61] = op('ADC', AM.INDIRECT_X);
OPCODES[0x65] = op('ADC', AM.ZERO_PAGE);
OPCODES[0x66] = op('ROR', AM.ZERO_PAGE);
OPCODES[0x68] = op('PLA', AM.IMPLIED);
OPCODES[0x69] = op('ADC', AM.IMMEDIATE);
OPCODES[0x6A] = op('ROR', AM.ACCUMULATOR);
OPCODES[0x6C] = op('JMP', AM.INDIRECT);
OPCODES[0x6D] = op('ADC', AM.ABSOLUTE);
OPCODES[0x6E] = op('ROR', AM.ABSOLUTE);

// 0x70 🤖
OPCODES[0x70] = op('BVS', AM.RELATIVE);
OPCODES[0x71] = op('ADC', AM.INDIRECT_Y);
OPCODES[0x75] = op('ADC', AM.ZERO_PAGE_X);
OPCODES[0x76] = op('ROR', AM.ZERO_PAGE_X);
OPCODES[0x78] = op('SEI', AM.IMPLIED);
OPCODES[0x79] = op('ADC', AM.ABSOLUTE_Y);
OPCODES[0x7D] = op('ADC', AM.ABSOLUTE_X);
OPCODES[0x7E] = op('ROR', AM.ABSOLUTE_X);

// 0x80 🤖
OPCODES[0x81] = op('STA', AM.INDIRECT_X);
OPCODES[0x84] = op('STY', AM.ZERO_PAGE);
OPCODES[0x85] = op('STA', AM.ZERO_PAGE);
OPCODES[0x86] = op('STX', AM.ZERO_PAGE);
OPCODES[0x88] = op('DEY', AM.IMPLIED);
OPCODES[0x8A] = op('TXA', AM.IMPLIED);
OPCODES[0x8C] = op('STY', AM.ABSOLUTE);
OPCODES[0x8D] = op('STA', AM.ABSOLUTE);
OPCODES[0x8E] = op('STX', AM.ABSOLUTE);

// 0x90 🤖
OPCODES[0x90] = op('BCC', AM.RELATIVE);
OPCODES[0x91] = op('STA', AM.INDIRECT_Y);
OPCODES[0x94] = op('STY', AM.ZERO_PAGE_X);
OPCODES[0x95] = op('STA', AM.ZERO_PAGE_X);
OPCODES[0x96] = op('STX', AM.ZERO_PAGE_Y);
OPCODES[0x98] = op('TYA', AM.IMPLIED);
OPCODES[0x99] = op('STA', AM.ABSOLUTE_Y);
OPCODES[0x9A] = op('TXS', AM.IMPLIED);
OPCODES[0x9D] = op('STA', AM.ABSOLUTE_X);

// 0xA0 🤖
OPCODES[0xA0] = op('LDY', AM.IMMEDIATE);
OPCODES[0xA1] = op('LDA', AM.INDIRECT_X);
OPCODES[0xA2] = op('LDX', AM.IMMEDIATE);
OPCODES[0xA4] = op('LDY', AM.ZERO_PAGE);
OPCODES[0xA5] = op('LDA', AM.ZERO_PAGE);
OPCODES[0xA6] = op('LDX', AM.ZERO_PAGE);
OPCODES[0xA8] = op('TAY', AM.IMPLIED);
OPCODES[0xA9] = op('LDA', AM.IMMEDIATE);
OPCODES[0xAA] = op('TAX', AM.IMPLIED);
OPCODES[0xAC] = op('LDY', AM.ABSOLUTE);
OPCODES[0xAD] = op('LDA', AM.ABSOLUTE);
OPCODES[0xAE] = op('LDX', AM.ABSOLUTE);

// 0xB0 🤖
OPCODES[0xB0] = op('BCS', AM.RELATIVE);
OPCODES[0xB1] = op('LDA', AM.INDIRECT_Y);
OPCODES[0xB4] = op('LDY', AM.ZERO_PAGE_X);
OPCODES[0xB5] = op('LDA', AM.ZERO_PAGE_X);
OPCODES[0xB6] = op('LDX', AM.ZERO_PAGE_Y);
OPCODES[0xB8] = op('CLV', AM.IMPLIED);
OPCODES[0xB9] = op('LDA', AM.ABSOLUTE_Y);
OPCODES[0xBA] = op('TSX', AM.IMPLIED);
OPCODES[0xBC] = op('LDY', AM.ABSOLUTE_X);
OPCODES[0xBD] = op('LDA', AM.ABSOLUTE_X);
OPCODES[0xBE] = op('LDX', AM.ABSOLUTE_Y);

// 0xC0 🤖
OPCODES[0xC0] = op('CPY', AM.IMMEDIATE);
OPCODES[0xC1] = op('CMP', AM.INDIRECT_X);
OPCODES[0xC4] = op('CPY', AM.ZERO_PAGE);
OPCODES[0xC5] = op('CMP', AM.ZERO_PAGE);
OPCODES[0xC6] = op('DEC', AM.ZERO_PAGE);
OPCODES[0xC8] = op('INY', AM.IMPLIED);
OPCODES[0xC9] = op('CMP', AM.IMMEDIATE);
OPCODES[0xCA] = op('DEX', AM.IMPLIED);
OPCODES[0xCC] = op('CPY', AM.ABSOLUTE);
OPCODES[0xCD] = op('CMP', AM.ABSOLUTE);
OPCODES[0xCE] = op('DEC', AM.ABSOLUTE);

// 0xD0 🤖
OPCODES[0xD0] = op('BNE', AM.RELATIVE);
OPCODES[0xD1] = op('CMP', AM.INDIRECT_Y);
OPCODES[0xD5] = op('CMP', AM.ZERO_PAGE_X);
OPCODES[0xD6] = op('DEC', AM.ZERO_PAGE_X);
OPCODES[0xD8] = op('CLD', AM.IMPLIED);
OPCODES[0xD9] = op('CMP', AM.ABSOLUTE_Y);
OPCODES[0xDD] = op('CMP', AM.ABSOLUTE_X);
OPCODES[0xDE] = op('DEC', AM.ABSOLUTE_X);

// 0xE0 🤖
OPCODES[0xE0] = op('CPX', AM.IMMEDIATE);
OPCODES[0xE1] = op('SBC', AM.INDIRECT_X);
OPCODES[0xE4] = op('CPX', AM.ZERO_PAGE);
OPCODES[0xE5] = op('SBC', AM.ZERO_PAGE);
OPCODES[0xE6] = op('INC', AM.ZERO_PAGE);
OPCODES[0xE8] = op('INX', AM.IMPLIED);
OPCODES[0xE9] = op('SBC', AM.IMMEDIATE);
OPCODES[0xEA] = op('NOP', AM.IMPLIED);
OPCODES[0xEC] = op('CPX', AM.ABSOLUTE);
OPCODES[0xED] = op('SBC', AM.ABSOLUTE);
OPCODES[0xEE] = op('INC', AM.ABSOLUTE);

// 0xF0 🤖
OPCODES[0xF0] = op('BEQ', AM.RELATIVE);
OPCODES[0xF1] = op('SBC', AM.INDIRECT_Y);
OPCODES[0xF5] = op('SBC', AM.ZERO_PAGE_X);
OPCODES[0xF6] = op('INC', AM.ZERO_PAGE_X);
OPCODES[0xF8] = op('SED', AM.IMPLIED);
OPCODES[0xF9] = op('SBC', AM.ABSOLUTE_Y);
OPCODES[0xFD] = op('SBC', AM.ABSOLUTE_X);
OPCODES[0xFE] = op('INC', AM.ABSOLUTE_X);

