const MESEN_ROM_OVERRIDES = Object.freeze({
  '009AF6BE': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '05104517': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  '0537322A': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  '09874777': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '0BDD8DD9': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '106180D6': { mapperNumber: 7, submapperNumber: 2 },
  '1248895C': { mapperNumber: 7, submapperNumber: 2 },
  '12B2C361': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '13D5B1A4': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  '1CEE0C21': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  '1EFE38EB': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  '2328046E': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AOROM' },
  '23D7D48F': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  '26535EF5': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '279710DC': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  '27CA0679': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  '2A662AC7': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AOROM' },
  '2B378D11': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AOROM' },
  '2D417253': { mapperNumber: 7, submapperNumber: 2 },
  '2E43FAA7': { mapperNumber: 7, submapperNumber: 2 },
  '308DA987': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  '31CBCD41': { mapperNumber: 7, submapperNumber: 2 },
  '3368F7FB': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AOROM' },
  '37138039': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '3F8C48FF': { mapperNumber: 7, submapperNumber: 1 },
  '3FEAFD85': { mapperNumber: 7, submapperNumber: 2 },
  '41D32FD7': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  '4220C170': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AOROM' },
  '4B041B6B': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  '4EB77C64': { mapperNumber: 7, submapperNumber: 2 },
  '505F9715': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '51BF28AF': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AMROM' },
  '524A5A32': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  '5C602471': { mapperNumber: 7, submapperNumber: 2 },
  '5DC9BC41': { mapperNumber: 7, submapperNumber: 1 },
  '5E6D9975': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '670C900A': { mapperNumber: 7, submapperNumber: 1 },
  '68383607': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '694C801F': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AOROM' },
  '6A88579F': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '6C4A9735': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '7CB0D70D': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '806DE21E': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  '8111BA08': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  '82E4EBBA': { mapperNumber: 7, submapperNumber: 2 },
  '8904149E': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  '898E4232': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  '89984244': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  '9198279E': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  '96CFB4D8': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  '9806CB84': { mapperNumber: 7, submapperNumber: 2, boardName: 'HVC-AOROM' },
  '9EDD2159': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  'A72FDE03': { mapperNumber: 7, submapperNumber: 2, boardName: 'HVC-AMROM' },
  'A8B1D1D1': { mapperNumber: 7, submapperNumber: 1 },
  'A91460B8': { mapperNumber: 7, submapperNumber: 2, boardName: 'HVC-AMROM' },
  'B5D10D5C': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AOROM' },
  'BDF046EF': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  'C0A650F8': { mapperNumber: 7, submapperNumber: 2 },
  'C1B43207': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  'C740EB46': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  'C8AD4F32': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  'CEB65B06': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AOROM' },
  'D2562072': { mapperNumber: 7, submapperNumber: 2, boardName: 'ACCLAIM-AOROM' },
  'DA2CB59A': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  'DB9C072D': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  'DD062F9C': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AN1ROM' },
  'E5A972BE': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AN1ROM' },
  'EB84C54C': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  'EB88D662': { mapperNumber: 7, submapperNumber: 2 },
  'EDCF1B71': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  'EFD26E37': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  'F518DD58': { mapperNumber: 7, submapperNumber: 2, boardName: 'NES-AMROM' },
  'F613A8F9': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-ANROM' },
  'FBF8A785': { mapperNumber: 7, submapperNumber: 1, boardName: 'NES-AOROM' },
  '0C48BADE': { mapperNumber: 34, submapperNumber: 2 },
  '162F1311': { mapperNumber: 34, submapperNumber: 2 },
  '1E36D20A': { mapperNumber: 34, submapperNumber: 2 },
  '274FAE3E': { mapperNumber: 34, submapperNumber: 2 },
  '3446EAE7': { mapperNumber: 34, submapperNumber: 2 },
  '368C19A8': { mapperNumber: 34, submapperNumber: 2 },
  '58011551': { mapperNumber: 34, submapperNumber: 2 },
  '5B8D4378': { mapperNumber: 34, submapperNumber: 2 },
  '92A3D007': { mapperNumber: 34, submapperNumber: 1, boardName: 'AVE-NINA-01' },
  '9E7590BA': { mapperNumber: 34, submapperNumber: 2 },
  'A21E675C': { mapperNumber: 34, submapperNumber: 2, boardName: 'IREM-BNROM' },
  'AC5C1840': { mapperNumber: 34, submapperNumber: 2 },
  'AD9F8ED6': { mapperNumber: 34, submapperNumber: 2 },
  'C2730C30': { mapperNumber: 34, submapperNumber: 2, boardName: 'NES-BNROM' },
  'CDF55296': { mapperNumber: 34, submapperNumber: 2 },
  'E645B187': { mapperNumber: 34, submapperNumber: 2 },
  'F407377E': { mapperNumber: 34, submapperNumber: 2 }
});

export function lookupMesenRomOverride(crc32Hex, mapperNumber = null) {
  const key = String(crc32Hex || '').toUpperCase();
  if (!key) return null;

  const override = MESEN_ROM_OVERRIDES[key] || null;
  if (!override) return null;
  if (mapperNumber != null && (override.mapperNumber | 0) !== (mapperNumber | 0)) return null;
  return override;
}
